name: Publish to NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build, Test, Pack & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal --settings coverage.runsettings --collect:"XPlat Code Coverage"

      - name: Generate Code Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: 'tests/**/TestResults/**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;MarkdownSummary'

      - name: Publish Coverage Summary to GitHub Step Summary
        run: cat coveragereport/Summary.md >> $GITHUB_STEP_SUMMARY

      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-publish-nuget
          path: |
            tests/**/TestResults/**/coverage.cobertura.xml
            coveragereport/

      - name: Pack package
        run: dotnet pack src/LevelGen/LevelGen.csproj --no-build --configuration Release --output nupkg

      - name: NuGet Login
        id: login
        uses: NuGet/login@v1
        with:
          user: JohnStrandGH

      - name: Publish to NuGet.org
        run: dotnet nuget push nupkg/*.nupkg --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
